version: '3.8'
services:
    php-apache:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./www:/var/www/html/
        ports:
            - 8000:80
        links:
            - db

    db:
        container_name: db
        image: mysql
        #image: mysql:8.0.29-debian
        #command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
            MYSQL_ROOT_HOST: '%'
        ports:
            - "9906:3306"


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
